application: nitish-cs253
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /final/stylesheet
  static_dir: final/templates/stylesheet

- url: /custom404
  static_dir: 404/static

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest
